### ISSUE TITLE
Create a BDD .feature file and accompanying steps.py files

### ISSUE THREAD

**Issue by ajaffery08** [DevOpsWishlist/wishlists#44]
**As a** developer
**I need** a feature file
**So that** I can implement automated BDD testing and test my RESTful APIs from the outside in

**Assumptions:** 
* 7 Scenarios in the feature file for all of CRUD + List + Query + Action

**Acceptance Criteria:**
* Feature will be written in Gherkin syntax
* This will test the RESTful APIs from the UI (outside in) perspective
* Using Selenium for UI testing
* BDD tests should not interact with the service and should only test the web interface

Given a feature file
When I have the BDD tests for all the appropriate scenarios
Then all the test scenarios should pass (should be green)
```

**Comment by wyam1** [comment]
Two new issues to be created:
- Create feature file for wishlists CRUD
- Create feature file for Items CRUD
