### ISSUE TITLE
Create a Wishlist

### ISSUE THREAD

**Issue by jku8** [DevOpsWishlist/wishlists#5]
**As a** customer
**I need** to be able to create a wishlist which contains a item/items I _wish_ I can purchase
**So that** I can revisit the item/items I wish I had and purchase at a later date OR share with someone who can purchase for me

**Assumptions:** 
api/v1/wish/1, POST
* Wishlist will have unique URL path based on its name
* Wishlist is a separate section/page/microservice in the eCommerce website
* Customer will always be able to create a new resource/wishlist even if a wishlist already exists

**Acceptance Criteria:**
```
Given I'm browsing products on an eCommerce website
When I'm on any page of the eCommerce website
Then I should be able to create a new wishlist (which will later allow me to add/delete specific products into the wishlist)
```

**Comment by ajaffery08** [comment]
test comment
